### ISSUE TITLE
Get Failed to find Element even though element id exists.

### ISSUE THREAD

**Issue by pittengermd** [y21/tl#11]
Code to reproduce error.
Cargo.toml
```
[dependencies]
reqwest = { version = "*", features = ["blocking", "json"] }
tl = { version = "*", features = ["simd"] }
```
main.rs
```
use std::{
    fs::File,
    io::{self, BufRead, BufReader, Write},
    path::Path,
};
use tl::{ VDom, Parser};

fn get_block(id: &str, parser: &Parser, dom: &VDom) {
    println!("id is: {}", id);
    let element = dom.get_element_by_id(id)
        .expect("Failed to find element")
        .get(parser)
        .unwrap();
    println!("Inner HTML: {:?}", element.inner_html());
    println!("Inner TEXT: {:?}", element.inner_text(parser));
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let resp = reqwest::blocking::get("https://www.thefreespeechforum.com")?.text()?;
    let mut html_file = File::create("tfsf_offline.html")?;
    html_file.write(resp.as_bytes())?;

    let dom = tl::parse(resp.as_str(), tl::ParserOptions::default());
    let parser = dom.parser();

    get_block("u54423", &parser, &dom);
    get_block("u54389-4", &parser, &dom);

    Ok(())
}
```

The second get_block works as expected.  But the first one fails to find the element, even though I have manually confirmed that the id does exist.  It is also not a problem with finding a id's because the second get_block call is also is also an a id.  

Screenshot showing that the id does actually exist.

![Screenshot from 2021-12-24 12-59-29](https://user-images.githubusercontent.com/27784772/147369567-71355442-f483-4321-9f2b-34c8655cabd4.png)

**Comment by y21** [comment]
Thanks for the report!

Reduced test case that fails:
```rs
let input = r#"
<a id="u54423">
    <iframe allowfullscreen></iframe>
</a>
"#;

let dom = parse(input, ParserOptions::default());
let element = dom.get_element_by_id("u54423");

assert!(element.is_some());
```
Looks like the `allowfullscreen` valueless attribute of the inner iframe tag causes a silent error, which in turn causes its parent tag to not be in the DOM tree.

**Comment by pittengermd** [comment]
Wow, thanks for the quick response!  Unfortunately I don't have the option of changing the html.  Where might I start looking to attempt to fix the bug.  If I can get a good fix I can submit a pull request, if you don't beat me to it :smile:

**Comment by y21** [comment]
Indeed the bug is in `Parser::parse_attributes` (in particular line 197):
https://github.com/y21/tl/blob/fa3fd1c6986c6e94ac9b1735fad34a8409a17ded/src/parser/base.rs#L197

It always advances the cursor after every attribute to skip quotes (i.e. the last `"` in `<a href="/"></a>`). Then, on the next iteration, it skips unnecessary whitespaces and checks if the current character (which in this case would be `>`), is one of `['/', '>']`. If it is, it returns from `parse_attributes` with all matches as it's done parsing the attributes.

However, when there *is no quote* (or no value at all), this gets buggy. For example, given `<a href></a>`, the function would skip the `>` as it wrongly assumes that the current character is a quote. This is bad, because now it interprets the rest of the string as more attributes.

One way to fix this would be to only advance the input stream if the character is not `>`.
```rs
if self.stream.current_cpy() != Some(b'>') {
  self.stream.advance();
}
```

Would you like to try to fix this in a PR or do you want me to?

Also, while looking through the code, I found another bug (unquoted attribute values not being parsed properly), but I'd like to fix that in a separate PR because that's a bit more complex.

**Comment by pittengermd** [comment]
I'll get started on the pull request as it would be a good chance for me to one contribute and two to get more familiar with your crate!  That would free you up to tackle the more complex PR.  If I finish this one, I'd love to collaborate with you on the next PR, if I wouldn't get in your way.

**Comment by y21** [comment]
> I'll get started on the pull request as it would be a good chance for me to one contribute and two to get more familiar with your crate! 

Sounds good :)

> If I finish this one, I'd love to collaborate with you on the next PR, if I wouldn't get in your way.

Sure, I opened a separate issue for tracking this: #12. It's actually not as complex as I made it sound like, but it means creating (or changing an existing method) and some additions involving SIMD (`Parser::read_to` needs to search for more than one byte).
